# Generated by Django 4.2.10 on 2024-10-24 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Abreviatura'),
        ),
        migrations.AddField(
            model_name='department',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('reference_code', models.CharField(blank=True, max_length=250, unique=True)),
                ('user_department', models.CharField(blank=True, max_length=250, null=True)),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'referencia',
                'verbose_name_plural': 'referencias',
                'db_table': 'referencia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('recipient', models.CharField(blank=True, max_length=200, null=True, verbose_name='Destinatário')),
                ('job', models.CharField(blank=True, max_length=200, null=True, verbose_name='Função')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cidade')),
                ('entity', models.CharField(blank=True, max_length=200, null=True, verbose_name='Entidade')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Assunto')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Conteúdo')),
                ('date_sent', models.DateTimeField(verbose_name='Data de expedição')),
                ('status', models.CharField(choices=[('', 'Selecione uma opção'), ('drafted', 'Rascunho'), ('submitted', 'Submetida para Aprovação'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('sent', 'Enviada')], default='', max_length=20, verbose_name='Estado')),
                ('coment_rejected', models.TextField(blank=True, null=True, verbose_name='Comentário de rejeição')),
                ('coment_review', models.TextField(blank=True, null=True, verbose_name='Comentário de revisão')),
                ('protocol', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Protocolo')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.department')),
                ('reference_code', models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.CASCADE, to='erp.reference', verbose_name='Código de referência')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'carta',
                'verbose_name_plural': 'cartas',
                'db_table': 'carta',
                'ordering': ['id'],
            },
        ),
    ]
