# Generated by Django 4.2.10 on 2024-10-24 16:01

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_department_abbreviation_department_counter_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
