# Generated by Django 4.2.10 on 2024-06-05 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
                ('desc', models.TextField(blank=True, max_length=400, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'cargo',
                'verbose_name_plural': 'cargos',
                'db_table': 'cargo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
                ('desc', models.TextField(blank=True, max_length=400, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'tipo',
                'verbose_name_plural': 'tipos',
                'db_table': 'tipo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('start_date', models.DateField(verbose_name='data de inicio')),
                ('end_date', models.DateField(verbose_name='data de fim')),
                ('status', models.CharField(blank=True, choices=[('PENDENTE', 'PENDENTE'), ('REJEITADO', 'REJEITADO'), ('APROVADO', 'APROVADO')], default='PENDENTE', max_length=20, null=True, verbose_name='estado')),
                ('obs', models.TextField(blank=True, max_length=400, null=True, verbose_name='descrição')),
                ('days_absence', models.PositiveIntegerField(blank=True, null=True, verbose_name='periodo')),
                ('reason', models.TextField(max_length=400, verbose_name='motivo da ausência')),
                ('type', models.ForeignKey(default='Selecione o tipo', on_delete=django.db.models.deletion.CASCADE, to='homepage.type', verbose_name='tipo da ausência')),
            ],
            options={
                'verbose_name': 'ausencia',
                'verbose_name_plural': 'ausencias',
                'db_table': 'ausencia',
                'ordering': ['reason'],
                'permissions': (('approve_absense', 'Can approve ausencia'), ('approve_up_absense', 'Can up approve ausencia')),
            },
        ),
    ]
