# Generated by Django 4.2.10 on 2024-06-11 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absence',
            options={'ordering': ['type'], 'permissions': (('aprove_absence', 'Can aprove ausencia'), ('aprove_up_absence', 'Can up aprove ausencia')), 'verbose_name': 'ausencia', 'verbose_name_plural': 'ausencias'},
        ),
        migrations.AlterField(
            model_name='absence',
            name='days_absence',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='end_date',
            field=models.DateField(verbose_name='Data de fim'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='obs',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Obs'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='reason',
            field=models.TextField(max_length=400, verbose_name='Motivo da ausência'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='start_date',
            field=models.DateField(verbose_name='Data de inicio'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDENTE', 'PENDENTE'), ('REJEITADO', 'REJEITADO'), ('APROVADO', 'APROVADO')], default='PENDENTE', max_length=20, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='type',
            field=models.ForeignKey(default='Selecione o tipo', on_delete=django.db.models.deletion.CASCADE, to='homepage.type', verbose_name='Tipo da ausência'),
        ),
    ]
