# Generated by Django 4.2.10 on 2024-07-01 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_absence_options_alter_absence_days_absence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de fim'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='reason',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Motivo da ausência'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de inicio'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.type', verbose_name='Tipo da ausência'),
        ),
    ]
