# Generated by Django 4.2.10 on 2024-08-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_absence_end_date_alter_absence_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absence',
            options={'ordering': ['id'], 'permissions': (('aprove_absence', 'Can aprove ausencia'), ('aprove_up_absence', 'Can up aprove ausencia')), 'verbose_name': 'ausencia', 'verbose_name_plural': 'ausencias'},
        ),
    ]
